version: "3.6"
services:
  webserver:
    image: nginx:1.21.5
    container_name: blog_webserver
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - blog_net

  database:
    image: postgres:14.2
    container_name: blog_database
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - blog_net

  php:
    build: docker/php
    container_name: blog_php
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    networks:
      - blog_net

networks:
  blog_net:
    name: blog_net
    driver: bridge
